//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionTireapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incidencia
    {
        public int IncidenciasID { get; set; }
        public Nullable<int> CamionID { get; set; }
        public Nullable<int> Neumatico_ID { get; set; }
        public string clase { get; set; }
        public string Posicion { get; set; }
        public Nullable<decimal> Presion { get; set; }
        public Nullable<decimal> Desgaste_Promedio { get; set; }
        public string estado { get; set; }
        public string observacion { get; set; }
        public string usureg { get; set; }
        public Nullable<System.DateTime> fecreg { get; set; }
        public string usumod { get; set; }
        public Nullable<System.DateTime> fecmod { get; set; }
    }
}
