//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionTireapp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TireappssEntities : DbContext
    {
        public TireappssEntities()
            : base("name=TireappssEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Camion> Camion { get; set; }
        public virtual DbSet<Camion_neumaticos> Camion_neumaticos { get; set; }
        public virtual DbSet<Departamento> Departamento { get; set; }
        public virtual DbSet<Distrito> Distrito { get; set; }
        public virtual DbSet<Empresa> Empresa { get; set; }
        public virtual DbSet<Grupoempresa> Grupoempresa { get; set; }
        public virtual DbSet<Incidencia> Incidencia { get; set; }
        public virtual DbSet<Lectura> Lectura { get; set; }
        public virtual DbSet<Menu> Menu { get; set; }
        public virtual DbSet<Neumatico> Neumatico { get; set; }
        public virtual DbSet<Opcion> Opcion { get; set; }
        public virtual DbSet<Perfil> Perfil { get; set; }
        public virtual DbSet<Permiso> Permiso { get; set; }
        public virtual DbSet<Provincia> Provincia { get; set; }
        public virtual DbSet<Tabla> Tabla { get; set; }
        public virtual DbSet<Tipo_neumatico> Tipo_neumatico { get; set; }
        public virtual DbSet<Tipodocumento> Tipodocumento { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Usuario_Perfil> Usuario_Perfil { get; set; }
    }
}
