//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionTireapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permiso
    {
        public int permiso_ID { get; set; }
        public Nullable<int> perfil_id { get; set; }
        public Nullable<int> menu_id { get; set; }
        public Nullable<int> opcion_id { get; set; }
        public string permite { get; set; }
        public string usureg { get; set; }
        public Nullable<System.DateTime> fecreg { get; set; }
        public string usumod { get; set; }
        public Nullable<System.DateTime> fecmod { get; set; }
    
        public virtual Menu Menu { get; set; }
        public virtual Opcion Opcion { get; set; }
        public virtual Perfil Perfil { get; set; }
    }
}
