//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionTireapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tabla
    {
        public int Tabla_ID { get; set; }
        public string codigo { get; set; }
        public string valor { get; set; }
        public Nullable<int> tabla_padre { get; set; }
        public string flag { get; set; }
        public string flag1 { get; set; }
        public string flag2 { get; set; }
        public string flag3 { get; set; }
        public Nullable<int> flagNum { get; set; }
        public Nullable<int> flagNum2 { get; set; }
        public Nullable<decimal> flagDec { get; set; }
        public Nullable<decimal> flagDec2 { get; set; }
        public string flagActivo { get; set; }
        public string comentario { get; set; }
        public Nullable<int> orden { get; set; }
        public string usureg { get; set; }
        public Nullable<System.DateTime> fecreg { get; set; }
        public string usumod { get; set; }
        public Nullable<System.DateTime> fecmod { get; set; }
    }
}
