//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionTireapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipo_neumatico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tipo_neumatico()
        {
            this.Neumatico = new HashSet<Neumatico>();
        }
    
        public int tipo_neumatico_ID { get; set; }
        public Nullable<int> empresa_id { get; set; }
        public string marca { get; set; }
        public string modelo { get; set; }
        public Nullable<int> ancho { get; set; }
        public string perfil { get; set; }
        public string radial { get; set; }
        public Nullable<decimal> altura_max { get; set; }
        public Nullable<decimal> altura_min { get; set; }
        public string indice_carga { get; set; }
        public string indice_velocidad { get; set; }
        public Nullable<int> desgaste { get; set; }
        public Nullable<decimal> temperatura { get; set; }
        public Nullable<decimal> precio { get; set; }
        public Nullable<decimal> presion_min { get; set; }
        public Nullable<decimal> presion_max { get; set; }
        public string estado { get; set; }
        public string usureg { get; set; }
        public Nullable<System.DateTime> fecreg { get; set; }
        public string usumod { get; set; }
        public Nullable<System.DateTime> fecmod { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Neumatico> Neumatico { get; set; }
    }
}
